HomeWork
ok-technopolis-autumn-2019/igor-laryushin pull request #1
Opened 2019-10-08 22:08 UTC by igorlaryush

2019-10-09 06:02 UTC, fromanywhere requested changes

2019-10-09 06:02 UTC, fromanywhere commented on style.css
> +.todos-header {
Не нужно коммитить этот файл

2019-10-09 06:02 UTC, fromanywhere commented on style.css
> +  letter-spacing: -2.5px;
Так делать никогда не надо, ломается геометрия шрифта

2019-10-09 06:02 UTC, fromanywhere commented on style.css
> +  line-height: 21px;
Здесь выглядит странно — интерлиньяж в пикселах меньше, чем кегль, в жизни такого не бывает

2019-10-09 06:02 UTC, fromanywhere commented on index.html
> +<!DOCTYPE html>
В дз по html нужно больше html!

2019-10-09 06:02 UTC, fromanywhere commented on index.html
> +  <h2 class="todos-header">todos</h2>
а почему h2?

2019-10-09 06:02 UTC, fromanywhere commented on index.html
> +  <div id="enterLine" class="header">
Какова причина использования id?

2019-10-09 06:02 UTC, fromanywhere commented on index.html
> +    <span onclick="newElement()" class="add">
Никогда не используйте инлайновые обработчики js (даже если кажется, что оно как в react, не надо — оно там работает не так)

2019-10-09 06:02 UTC, fromanywhere commented on index.html
> +      <button type="button" name="button"></button>
Здесь и ниже работаем над доступностью (a11y)

2019-10-09 06:02 UTC, fromanywhere commented on index.html
> +    <ul class = "task-list">
Прогон форматирования через prettier

2019-10-09 06:02 UTC, fromanywhere commented on index.html
> +        <label class = "dfg">
Define future goal? Don't forget garbage?

2019-10-09 06:02 UTC, fromanywhere commented on index.html
> +  <div class="buttom-bar">
Здесь проблемы с компонентизацией — плоский список элементов, а следовало бы выделить логический независимый блок фильтра

2019-10-29 19:09 UTC, igorlaryush commented
@fromanywhere

2019-10-29 19:35 UTC, fromanywhere commented
> @fromanywhere

давайте разделим этот pr на два, как полагается — отдельно на дз по html, я его сразу проаппрувлю, и второй, про css, его мы будем обсуждать. Как минимум там графика не приезжает

2019-10-29 21:10 UTC, closed without merging